# Generated by Django 2.2.1 on 2019-05-15 12:42

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import wcg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('font_file', models.FileField(upload_to=wcg.models.Font.font_path)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(default='unknown', max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('data', models.TextField(default='')),
                ('mask_image', models.ImageField(blank=True, upload_to=wcg.models.Request.mask_image_path)),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('font', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='wcg.Font')),
            ],
        ),
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcg.Request')),
            ],
        ),
    ]
