# Generated by Django 2.2.1 on 2019-05-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oredered_at',
            new_name='ordered_at',
        ),
    ]
