# Generated by Django 2.2.1 on 2019-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloud',
            name='wordCloud',
            field=models.FilePathField(default='/'),
            preserve_default=False,
        ),
    ]
