# Generated by Django 2.2.1 on 2019-05-08 05:42

from django.db import migrations, models
import wcg.models


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloud',
            name='mask_image',
            field=models.ImageField(upload_to=wcg.models.user_path),
        ),
    ]
