# Generated by Django 2.2.1 on 2019-05-08 06:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0002_auto_20190508_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloud',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
