# Generated by Django 2.2.1 on 2019-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0002_wordcloud_wordcloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloud',
            name='wordCloud',
            field=models.FilePathField(default='/'),
        ),
    ]
