# Generated by Django 2.2.1 on 2019-05-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0002_auto_20190516_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=100),
        ),
    ]
