# Generated by Django 2.2.1 on 2019-05-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0003_auto_20190516_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_at',
        ),
    ]
