# Generated by Django 2.2.1 on 2019-05-08 06:10

from django.db import migrations, models
import wcg.models


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0003_auto_20190508_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloud',
            name='mask_image',
            field=models.ImageField(upload_to=wcg.models.mask_path),
        ),
    ]
