# Generated by Django 2.2.1 on 2019-05-08 07:16

from django.db import migrations, models
import wcg.models


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0004_auto_20190508_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.FilePathField(path=wcg.models.font_path)),
            ],
        ),
        migrations.RenameModel(
            old_name='WordCloud',
            new_name='WordCloudModel',
        ),
    ]
