# Generated by Django 2.2.1 on 2019-05-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0005_auto_20190515_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloud',
            name='wordCloud',
            field=models.FileField(upload_to=''),
        ),
    ]
