# Generated by Django 2.2.1 on 2019-05-15 13:37

from django.db import migrations, models
import wcg.models


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0006_auto_20190515_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcloud',
            name='wordCloud',
            field=models.FileField(blank=True, upload_to=wcg.models.WordCloud.word_cloud_path),
        ),
    ]
