# Generated by Django 2.2.1 on 2019-05-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0006_wordcloudmodel_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FontModel',
            new_name='Font',
        ),
        migrations.RenameModel(
            old_name='WordCloudModel',
            new_name='WordCloud',
        ),
    ]
