# Generated by Django 2.2.1 on 2019-05-15 06:13

from django.db import migrations, models
import wcg.models


class Migration(migrations.Migration):

    dependencies = [
        ('wcg', '0008_auto_20190515_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=wcg.models.MaskImage.mask_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
